# Generated by Django 5.0 on 2024-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolclassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('fatherName', models.CharField(max_length=150)),
                ('motherName', models.CharField(max_length=150)),
                ('roll', models.IntegerField()),
                ('cl_name', models.ManyToManyField(to='student.schoolclassmodel')),
            ],
        ),
    ]
